sudo: false
language: python
services:
- docker
python:
- '3.8'
script:
- docker build .
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  password:
    secure: MIiFqUQ17pUguVJ9AodG9i2CFVxksdoeVt6HEGOi7Vk5estXvzREloeFhNdQ5qnDhNXB3qgznZsjiBa1xM0x+9Ne2NaWkjTFPhG2l0xAW2b0bwrh7f+9CtqOwhQwU940PL1O6GYPdjW1DP+G7y6Sh7gM/3TZYiuR6o96jQsILs6yEGzfrNIwmp2sUhOf6vUjxAg9Q7d5JHQTtrq0dwNNkIa63OEJfaWV3APm5jbhWiWJK7MmPFiE835Z8n24+Fqsn7BQ6yWQMg+OMXqZoZkmPy5B5wxPLDG3DVGQw712HjXsedtTRgf9rfsv4+lQD5NKnBBku0J7FD06Yc1+dsce8qtH8uTRKUJ6oyJfiUsu1KUyEo8gJ4/2ECuwhMP3P5n+5W8n/z6OOL0IY3bsAnYKhVshj+2WfSr/ip819f5z3KpCU96NI5OMvMjdxJXqNOPa0dqUsvH5JhfyUEiozVxeN5cKVogJMvkoA6Bz6J9IxC83oiIMYVLAgQghJGk0e4Q3Zz8WW5jBOvVJx+5yhaOCCAIffGxrS1cSL3zaDzMoRJZpsnuhefCw6mvK5OPbTUsMGmX0VhO8oakcz8gxk/RoSTBXuWRkTazvZ6TyfVEhUMKaZuWKJlOn1z4BiLBOwnwN9NDqxfD1ML89nDeyW9OrsN9MySIYuKi8QMY8X9yj/mk=
