sudo: false
language: python
services:
- docker
python:
- '3.8'
script:
- docker build .
deploy:
  provider: pypi
  user: __token__
  on:
    tags: true
  password:
    secure: nMjg6xIi6wPruZxXNZ1sc2Ov0JsidPCt15JJsCv844brQc86sO6iwLn9fUsdH0y3kh2Dfqs5PR8Q7ld1lB4OLZLLGnb27Gt7OqGXSQGMvikt5QaO7bKnT/WhSuPNJjOuxLXlZa3gQsGve60hAGQG2xgfayalpkQh1tUvNWDW2QsbPL47eeRry7g62QC8KoQLYCoVN2AplqRpD5pd1lcTmfGAGw08aDtPVH7r/yGshgsFHGFnNOvn6OWpRMRvz7wTkP1fSB/wU32mK51YZpP7o4RT19ITF4eaCBZt+azExJPeY0RN8s1IYqpJt+2IGJeDQ6xvsro9GwjcTq14C6ppxJmsj5BiW9yBcuFOYd1hP8NwgfQevfAvpXAfgzRX9NpeA+LnoNJtKAk/mSXekTXntm8Pled8lmfLjQCe6FLc9XDSy8CbLzzlqKiIVUZInzhc1JtStfcGUwkMyFf2XB08103nHSjn9SnG51Q3q68leqTryQhoOIrxVIZvdhP3ErWNZpmFrSSv044nyfxJXA+4eLGv0DQW7ZnVYvWmbd7be2jelTQiIwTCb8iBu939qe8tyq6WueuiobPQ/0IrfqNRpuIfdbdv/IAOifFyKHH7RkUegdLxsgZ4HqiGl4OWA5xGm+TK7OTrqKjDHG4AAYt1M2Hb+9bN0U9uaJrgDThX+NY=
