sudo: false
language: python
services:
- docker
python:
- '3.8'
script:
- docker build .
deploy:
  provider: pypi
  user: __token__
  on:
    tags: true
  password:
    secure: u969Yr8cQXn1nvgEVqGuIzHOlKeULiiNquet8xq5W74ZcwD6KecuBeBuBefwH/5xxOSWIvFbnlFKwyLvDxXOboTqtTjklcAHuqi7bmGuRZcOmHIISPneskz2DPnnmD5j8ZTi2Bf2dMrwqQAQlNtCyQ42gwONF3vNb+2vjxlY9wuo2r5EWRRm334GZEE65t+owAQ2mrskbkxndqmxC1X++E6nYPyFLX2b6/9TEiAhZbT8NzNX2yy2gBVZfoIjq65R8bJJyOWNUKDE20wJxX2G4nTRlQJV8FSPhOCUP5O/wKFuQLH3d5WuV7sspQEnnYfqvbOCyrCy/CJBXUGQRYap8xXugDPlW3/2FpwhYjzoztzX/CnykLAN7ggOR1l1bw3Fgomv+0papTzurixHIBPs5EzHhVT65feDuUstOks3iGFdBEsDn1fa68vLdU2d8P39zHh6dHWIOq/0bFWej6r0x5bRmUPRWs+Q9PDcq5RPues2fxx+ChiObonFYzwvqXG6DGJ28imqjSsaVD8lN39+S1b1ox9LET+uqUMYirWl/oY8tFErELi9cyitRr3JBWE+H9cYiGzqVCReJW9wLEjqQh959DqF6XZXbPNc1TGFPZxrKbN1zezxu9FxJL7ojyEx2rajmsGDfYiZXHjHnCA2YMdEJqlCTID3gyWGR9fhznI=
